name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@v3
        
        - uses: actions/setup-node@master
          with:
            node-version: 16.x

        - name: Verify commit exists in origin/main
          run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
            git branch --remote --contains | grep origin/main

        - name: Set VERSION variable from tag
          run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

        - name: Build
          run: dotnet build -c Release /p:Version=${VERSION}

        - name: Test
          run: dotnet test -c Release /p:Version=${VERSION} --no-build
        
        - name: Pack
          run: dotnet pack -c Release -o ./packages /p:Version=${VERSION} --no-build
        
        - name: Store Nuget Package 
          uses: actions/upload-artifact@v3
          with:
            name: hazelnutNuget
            path: ./packages/*.nupkg
        
        - name: Download Package
          uses: actions/download-artifact@v3
          with:
            name: hazelnutNuget
        
        - name: Push
          run: dotnet nuget push *.nupkg  --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate 
          
